name: local_database
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  decorated_icon: ^1.2.1
  eva_icons_flutter: ^3.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/